### ISSUE TITLE
lesson-8: График работает неверно

### ISSUE THREAD

**Issue by LehaIvanov** [Flowseal/TravelPractice#12]
Скидываю два скриншота с промежутком в 10 секунд. Из графиков видно, что на время 15:49:23 в одном случае цена составляет 0.85, а на другом графике 0.625, аналогично в 15:49:43 на одном графике 0.65, на другом 0.85

![image](https://github.com/Flowseal/TravelPractice/assets/13798121/a2c3496c-207f-4246-a452-83825f6453aa)

![image](https://github.com/Flowseal/TravelPractice/assets/13798121/82a53ebd-4446-457a-b760-d5fbb02ea624)

**Comment by Flowseal** [comment]
![image](https://github.com/Flowseal/TravelPractice/assets/50780822/c47dc9d7-8df9-46ea-bb99-393a16deafd8)
![image](https://github.com/Flowseal/TravelPractice/assets/50780822/70f80db5-25ad-4bfa-bbaa-46e6256290e4)
