### ISSUE TITLE
Типы в TS

### ISSUE THREAD

**Issue by AkshachRd** [Flowseal/TravelPractice#5]
https://github.com/Flowseal/TravelPractice/blob/7d15b55501316acb87d6be862a9dc46b971e96d9/Lesson7%20(React%20Reviews)/src/ReviewData.tsx#L1-L6
1) Напиши мне, пожалуйста, чем .tsx файлы отличаются от .ts и зачем они нужны.
2) Если я уберу из `ReviewData` слово Data, там перестанут лежать данные?)
Декларативно мы должны описывать то что видим глазами человека, не находящимся в программировании. 
Мне не нужно понимание, что avatar в base64. Мне нужно использовать аватар, и инкапсулировать его реализацию за названием. Я вижу просто `const avatar` и пользуюсь им.

**Comment by Flowseal** [comment]
1. В tsx файлах присутствует jsx код. Поправлю.
2. У меня есть компонент Review, поэтому я добавил постфикс Data, чтобы не было конфликта имён

**Comment by AkshachRd** [comment]
Можешь это использовать вот так `import { Review as ReviewData } from "./review.ts"`.
Либо придумать другое название для компонента или для типа. Эта Data вообще не вписывается.

**Comment by AkshachRd** [comment]
Насколько ты был значком с js, ts и react-ом до практики?
