### ISSUE TITLE
Возвращение JSX

### ISSUE THREAD

**Issue by AkshachRd** [Flowseal/TravelPractice#6]
https://github.com/Flowseal/TravelPractice/blob/1f88beb7cbaf2598fa70e6af9affa706245fb5b8/Lesson7%20(React%20Reviews)/src/components/ReviewsBlock/ReviewsBlock.tsx#L10-L32
Лучше знаешь как делать, чтобы у тебя внизу функции возвращалась всегда вёрстка как нужно, а условный рендеринг делать не вложено, а просто через условия до того, как ты вернёшь верстку.
Пример:
![image](https://github.com/Flowseal/TravelPractice/assets/29169528/f213f780-6298-480f-9f7e-cfdb17d67a2a)
а чтобы возвращать можно было null, поменять тип на React.ReactNode

**Comment by Flowseal** [comment]
О, понял, удобно. Сделаю.
