### ISSUE TITLE
Задание стилей элементу

### ISSUE THREAD

**Issue by AkshachRd** [Flowseal/TravelPractice#8]
https://github.com/Flowseal/TravelPractice/blob/1f88beb7cbaf2598fa70e6af9affa706245fb5b8/Lesson7%20(React%20Reviews)/src/components/NewReview/NewReview.tsx#L31-L32
В реакте мы фундаментально стараемся как меньше взаимодействовать с DOM, потому что подобные действия разрывают наш флоу работы приложения, и из-за этого оно работает медленнее и менее понятно. Также это недекларативно.
В таком случае обычно выносят всё что тебе нужно в классы в css файл, создают состояние типа `isTextAreaHightlighted` и в className пришут ```className={`${isTextAreaHightlighted && "textArea_highlighted"}`}```
В данном же случае, тебе надо задавать высоту динамически. Ты можешь сделать состояние `textAreaHight` типа number, менять его в `handleTextChange`, а в компоненте сделать переменную `textAreaStyles`, где и задавать стили, потом передавать это в пропсы.
Примерно так.
![image](https://github.com/Flowseal/TravelPractice/assets/29169528/86224f12-af13-4e0b-a58e-dd5f3a3cd049)
![image](https://github.com/Flowseal/TravelPractice/assets/29169528/388d68be-f722-45b2-9e66-99225325bff0)
![image](https://github.com/Flowseal/TravelPractice/assets/29169528/0b4b35b0-37a8-4105-83f9-00f448dece7b)
![image](https://github.com/Flowseal/TravelPractice/assets/29169528/aa0c553b-7fdd-4a58-93e2-a13b77131d54)
Переменная styles будет пересчитываться при каждом рендере, это нормально.
Любые манипуляции с DOM запрещены, элементы нужно брать через ref, а не по id.
![image](https://github.com/Flowseal/TravelPractice/assets/29169528/77da4c6c-6277-4c24-8661-3cb910c117f2)

**Comment by Flowseal** [comment]
Понял, исправлю
